language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"
# command to install dependencies
install:
  - pip install . --use-mirrors
  - pip install -r test_requirements.txt --use-mirrors
# only notify when status changes from success to failure
notifications:
  email:
    recipients:
      - code@ramiro.org
    on_failure: change
# command to run tests
script: nosetests