# General settings that will be available in templates.
site:
    base_url: http://localhost:8080
    disqus_shortname: null
    author: Author


# Settings that affect collections in the document index.
collections:
    tags:
        path: tags
        template: tag.html


# Content specific settings, at the moment only templates are specified.
content:
    index:
        template: index.html
    doc:
        template: page.html
    rss:
        template: rss2.xml