site:
  base_url: http://localhost:8080
  disqus_shortname: null
  author: Author

collections:
- path: tags
  var: tags

templates:
- content_type: index
  template: index.html
- content_type: doc
  template: post.html
- content_type: rss
  template: rss2.xml